import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getTranslations } from "next-intl/server";
import { JsonLd } from "@/components/repo/json-ld";
import { RepoHero } from "@/components/repo/repo-hero";
import { ReviewsPlaceholder } from "@/components/repo/reviews-placeholder";
import { ScoreBreakdown } from "@/components/repo/score-breakdown";
import { TagsList } from "@/components/repo/tags-list";
import { env } from "@/lib/env";
import { getRepo } from "@/lib/marketplace/queries";
// PageProps is a global type generated by Next 16 — do NOT import.

export async function generateMetadata(props: PageProps<"/r/[owner]/[name]">): Promise<Metadata> {
  const { owner, name } = await props.params;
  const repo = await getRepo(owner, name);
  if (!repo) return {};
  return {
    title: `${owner}/${name} — VibeShelf`,
    description: repo.description?.slice(0, 160) ?? undefined,
    openGraph: {
      title: `${owner}/${name}`,
      description: repo.description ?? undefined,
      images: repo.hero_asset?.external_url ? [{ url: repo.hero_asset.external_url }] : undefined,
    },
  };
}

export default async function RepoDetailPage(props: PageProps<"/r/[owner]/[name]">) {
  const { owner, name } = await props.params;
  const repo = await getRepo(owner, name);
  if (!repo) notFound(); // returns 404 status

  const t = await getTranslations("repo");
  const base = env.NEXT_PUBLIC_SITE_URL ?? "https://vibeshelf.example";
  const url = `${base}/r/${owner}/${name}`;

  return (
    <main className="container mx-auto px-4 py-6 space-y-8">
      <RepoHero repo={repo} />
      {repo.scores.total > 0 && <ScoreBreakdown axes={repo.scores} />}
      <TagsList
        tags={{
          feature: repo.feature_tags,
          tech_stack: repo.tech_stack_tags,
          vibecoding_tool: repo.vibecoding_tags,
        }}
      />
      {/*
        README full preview deferred to SP#4.5 (readme markdown not stored in DB per D4=Y).
        For MVP, render description as a plain summary section — NOT inside ReadmePreview
        which advertises "Documentation preview" and would mislead users/SEO.
      */}
      {repo.description && (
        <section aria-labelledby="summary-heading" className="space-y-2">
          <h2 id="summary-heading" className="text-lg font-semibold">
            {t("summary")}
          </h2>
          <p className="text-muted-foreground">{repo.description}</p>
        </section>
      )}
      <ReviewsPlaceholder />
      <JsonLd repo={{ ...repo, total_score: repo.scores.total }} url={url} />
    </main>
  );
}
