import { Suspense } from "react";
import { EmptyState } from "@/components/marketplace/empty-state";
import { FilterChips } from "@/components/marketplace/filter-chips";
import { FilterDrawer } from "@/components/marketplace/filter-drawer";
import { FilterSidebar } from "@/components/marketplace/filter-sidebar";
import { GridSkeleton } from "@/components/marketplace/grid-skeleton";
import { Pagination } from "@/components/marketplace/pagination";
import { RepoGrid } from "@/components/marketplace/repo-grid";
import { SortDropdown } from "@/components/marketplace/sort-dropdown";
import { getMarketplaceFacets } from "@/lib/marketplace/facets";
import { listRepos } from "@/lib/marketplace/queries";
import { parseMarketplaceParams } from "@/lib/marketplace/search-params";
// PageProps is a global type generated by Next 16 into .next/types/ — do NOT import.

export default async function Home(props: PageProps<"/">) {
  const sp = await props.searchParams;
  const query = parseMarketplaceParams(sp as Record<string, string | string[] | undefined>);
  const facets = await getMarketplaceFacets();

  return (
    <main className="container mx-auto px-4 py-6">
      <header className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">VibeShelf</h1>
          <p className="text-muted-foreground">Curated open-source templates for vibe coders</p>
        </div>
        <SortDropdown initial={query.sort} />
      </header>

      <FilterDrawer initial={query} facets={facets} />
      <FilterChips initial={query} />

      <div className="grid grid-cols-1 lg:grid-cols-[18rem_1fr] gap-6">
        <FilterSidebar initial={query} facets={facets} />
        <Suspense fallback={<GridSkeleton />}>
          <ReposSection query={query} />
        </Suspense>
      </div>
    </main>
  );
}

async function ReposSection({ query }: { query: ReturnType<typeof parseMarketplaceParams> }) {
  const { items, totalCount } = await listRepos(query);

  if (items.length === 0) {
    // Recommendations: top-scored repos when current query has no results.
    const recs = await listRepos({ sort: "score", page: 1, tags: [], categories: [] });
    return <EmptyState recommendations={recs.items.slice(0, 6)} />;
  }

  const totalPages = Math.max(1, Math.ceil(totalCount / 36));

  function buildHref(page: number): string {
    const url = new URLSearchParams();
    if (query.q) url.set("q", query.q);
    if (query.categories.length) url.set("categories", query.categories.join(","));
    if (query.tags.length) url.set("tags", query.tags.join(","));
    if (query.min_score !== undefined) url.set("min_score", String(query.min_score));
    if (query.vibecoding) url.set("vibecoding", query.vibecoding);
    if (query.sort !== "score") url.set("sort", query.sort);
    if (page !== 1) url.set("page", String(page));
    const qs = url.toString();
    return qs ? `/?${qs}` : "/";
  }

  return (
    <div>
      <p className="text-sm text-muted-foreground mb-3" role="status">
        {totalCount.toLocaleString()} template{totalCount === 1 ? "" : "s"} found
      </p>
      <RepoGrid repos={items} />
      <Pagination currentPage={query.page} totalPages={totalPages} buildHref={buildHref} />
    </div>
  );
}
