// Typed wrappers for the new SECURITY DEFINER RPCs added in the
// 20260414000002 migration. These RPCs are NOT in the committed
// `database.types.ts` because the file is auto-generated by
// `supabase gen types --local` and Docker is unavailable to run that
// locally. CI's "Generate and diff" step would fail if we hand-edited
// the generated file.
//
// Once the migration applies and `pnpm db:types` runs in an env with
// Docker, the generated Database type will include these RPCs and the
// `as any` casts below can be deleted in favor of `db.rpc(name, args)`
// directly.

import type { SupabaseClient } from "@/lib/db";

interface RpcRow {
  id: string;
  token_encrypted: string;
  token_key_version: number;
  remaining: number | null;
  reset_at: string | null;
}

interface RpcResult<T> {
  data: T;
  error: { message: string } | null;
}

export async function rpcAcquirePipelineLock(
  db: SupabaseClient,
  lockKey: string,
): Promise<RpcResult<boolean | null>> {
  // biome-ignore lint/suspicious/noExplicitAny: RPC type regen pending (Docker required)
  return (db.rpc as any)("acquire_pipeline_lock", { lock_key: lockKey });
}

export async function rpcReleasePipelineLock(
  db: SupabaseClient,
  lockKey: string,
): Promise<RpcResult<boolean | null>> {
  // biome-ignore lint/suspicious/noExplicitAny: RPC type regen pending (Docker required)
  return (db.rpc as any)("release_pipeline_lock", { lock_key: lockKey });
}

export async function rpcAcquireGithubToken(
  db: SupabaseClient,
  scope: string,
): Promise<RpcResult<RpcRow[] | null>> {
  // biome-ignore lint/suspicious/noExplicitAny: RPC type regen pending (Docker required)
  return (db.rpc as any)("acquire_github_token", { p_scope: scope });
}
